=== Install Terraform

 - Download : https://www.terraform.io/downloads.html

 - Unzip 
[source,shell]
----
$ unzip terraform-xxx-.zip -d /usr/local/terraform-xxx
$ rm /usr/local/terraform
$ ln -sf /usr/local/terraform-xxx /usr/local/terraform
----


Source : https://github.com/deverton/terraform-aws-consul

1. Once you have one, create an IAM user called *terraform* and save the *access key* and *secret key* that are given to you. Then ensure that the terraform user has the "Amazon EC2 Full Access" policy template applied either a via group or role.


2. To allow SSH access to the test VPC you must import your public key in to EC2.
[source,shell]
----
$ aws ec2 import-key-pair --public-key-material file://~/.ssh/id_rsa.pub --key-name terraform
----
Then 
[source,shell]
----
$ ssh -A ec2-user@$(terraform output bastion)
----

In the instance : 

[source,json]
----
resource "aws_instance" "bastion" {
    connection {
        user = "ec2-user"
        key_file = "${var.key_path}"
    }

ouput ip address
----


https://serverfault.com/questions/643647/how-to-ssh-to-ec2-instance-in-vpc-private-subnet-via-nat-server

If you create a new instance, as an overview, you will:

1) create a security group for your bastion host that will allow SSH access from your laptop (note this security group for step 4)

2) launch a separate instance (bastion) in a public subnet in your VPC

3) give that bastion host a public IP either at launch or by assigning an Elastic IP

4) update the security groups of each of your instances that don't have a public IP to allow SSH access from the bastion host. This can be done using the bastion host's security group ID (sg-#####).

5) use SSH agent forwarding (ssh -A user@publicIPofBastion) to connect first to the bastion, and then once in the bastion,SSH into any internal instance (ssh user@private-IP-of-Internal-Instance). Agent forwarding takes care of forwarding your private key so it doesn't have to be stored on the bastion instance (never store private keys on any instance!!)
Be sure to allow SSH/22 on both inbound and outbound on the bastion. – user464180 Nov 3 '15 at 16:22 


Common Ingress/Egress rules : 

TCP:

    80/443: Web Traffic (Port 80 and 443 are ports generally associated with "the Internet". Port 443/HTTPS is the HTTP protocol over TLS/SSL. Port 80/HTTP is the World Wide Web. Let's face it, port 80/443 are generally a given for being open on any type of filtering device allowing traffic outbound on your network.) 
    20/21: FTP
    22: SSH
    25/587: Mail (limit this to your SMTP server)
    53: Domain Transfer or DNS (again, limit to your trusted DNS server for the most part)
    110/995: POP3/POP3S (Limit to your mail server)
    123: Network Time Protocol (limit to trusted time servers)
    143/220/993: IMAP2/IMAP3/IMAPs2
    5190: AOL Instant Messenger
    5222/5223: Google Talk

ICMP :
 
  -1: for ping ?

UDP:

    53: DNS (limit this to your trusted DNS servers only)
    123: Network Time Protocol (limit to trusted time servers)



# Public and Private network : https://nickcharlton.net/posts/terraform-aws-vpc.html
# Nat Gateway : https://charity.wtf/2016/04/14/scrapbag-of-useful-terraform-tips/
# Kubernetes : http://www.devoperandi.com/kubernetesterraform-multiple-availability-zone-deployments/
# How do I connect a public-facing load balancer to EC2 instances that have private IP addresses? : https://aws.amazon.com/premiumsupport/knowledge-center/public-load-balancer-private-ec2/


Overview of AWS services : https://www.airpair.com/aws/posts/building-a-scalable-web-app-on-amazon-web-services-p1
Mysql Aurora cluster : http://www.davidbegin.com/building-a-mysql-da/
KOPS : 
    https://blog.mrtrustor.net/post/gitlab-on-k8s/
    https://www.datawire.io/guide/infrastructure/setting-kubernetes-aws/

=== DNS With Route53 

[source,json]
----
resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true
...
 }
----

Route53 : https://github.com/yakhyadabo/terraform-ec2/commit/27c1849b7b8e36551182eea8f1a605551a4fab57

=== Classic vs Application LB : https://cloudacademy.com/blog/application-load-balancer-vs-classic-load-balancer/
