runcmd:

# Install docker
  - sudo yum install -y docker > /tmp/docker.log
  - sudo systemctl start docker

# Run nginx
  - sudo docker run -d --name nginx -p 8080:80 nginx


# Run Postgres
# - sudo docker run --name wordpressdb -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=wordpress -d mysql:5.7
# - sudo docker run --rm --name wordpress -e WORDPRESS_DB_HOST=db.internal.com -e WORDPRESS_DB_NAME=wordpress -e WORDPRESS_DB_USER=wordpresss -e WORDPRESS_DB_PASSWORD=badpassword -p 8080:80  wordpress 

